CREATE TABLE role (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR (50) NOT NULL UNIQUE
);

CREATE TABLE user (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR (100) NOT NULL,
	password VARCHAR (100) NOT NULL,
	enable BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role_user (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES user(id),
    FOREIGN KEY (role_id) REFERENCES role(id)
);

INSERT INTO role (name) VALUES ('CLIENT');
INSERT INTO role (name) VALUES ('PROVIDER');
INSERT INTO role (name) VALUES ('ADMIN');
